Repository theQRL/qrl-wallet, pull requests merged in 2018-07, with the labels that each got.

#244 Mobile UI into devnet
  imports/startup/client/routes.js
  imports/ui/mobile/mobile.html
  imports/ui/mobile/mobile.js
  imports/ui/pages/create/address.html
  imports/ui/pages/create/create.html
  imports/ui/pages/open/open.html
  imports/ui/pages/tokens/tokenCreate.html
  imports/ui/pages/tokens/tokenCreateConfirm.html
  imports/ui/pages/tokens/tokenCreateResult.html
  imports/ui/pages/tools/notarise/start.html
  imports/ui/pages/tools/tools.html
  imports/ui/pages/transfer/transfer.html
  imports/ui/pages/verify/verify.html
  imports/ui/stylesheets/overrides.css
  package-lock.json
  package.json
  public/img/icons/cogs.svg
  public/img/icons/verify.svg
Labels: Priority: Medium, Status: In Progress, Type: Enhancement

#246 Mobile UI bug fixes
  imports/startup/client/routes.js
  imports/ui/pages/open/open.html
  imports/ui/pages/tokens/tokenCreateConfirm.html
  imports/ui/pages/tokens/tokenCreateResult.html
  imports/ui/stylesheets/overrides.css
Labels: Priority: Low, Status: Completed, Type: Bug

#248 Improved mobile UI (#247)
  imports/startup/client/routes.js
  imports/ui/mobile/mobile.html
  imports/ui/mobile/mobile.js
  imports/ui/pages/create/address.html
  imports/ui/pages/create/create.html
  imports/ui/pages/open/open.html
  imports/ui/pages/tokens/tokenCreate.html
  imports/ui/pages/tokens/tokenCreateConfirm.html
  imports/ui/pages/tokens/tokenCreateResult.html
  imports/ui/pages/tools/notarise/start.html
  imports/ui/pages/tools/tools.html
  imports/ui/pages/transfer/transfer.html
  imports/ui/pages/verify/verify.html
  imports/ui/stylesheets/overrides.css
  package-lock.json
  package.json
  public/.DS_Store
  public/img/.DS_Store
  public/img/icons/.DS_Store
  public/img/icons/cogs.svg
  public/img/icons/verify.svg
Labels: Status: Completed, Type: Enhancement

#251 Fixing token transfer txn bug in transaction list
  imports/startup/server/index.js
  package-lock.json
Labels: Priority: High, Status: Completed, Type: Bug
